### ISSUE TITLE
incorrect handling of tied scores

### ISSUE THREAD

**Issue by Conarus** [Pezmc/Quiz-Scoreboard#3]
Whenever 2 people are tied it correctly skips tyhe next position (i.e tied for 3rd, then next is 5th), but then it skips a position for all subsequent positions (i.e scoreboard shows, 3rd, 3rd, 5th, 7th, 9th) and this further compounds for any future ties.

Sorry I've no programming knowledge to fix this but would love to use it for a charity table quiz scoreboard.

**Comment by Pezmc** [comment]
I've thrown together a quick fix in 6bc40bfc0edde163455ae2ba7ab4a110176c31ba, I hope that helps!
