### ISSUE TITLE
Still handling tied scores incorrectly

### ISSUE THREAD

**Issue by Conarus** [Pezmc/Quiz-Scoreboard#4]
#3 was improved as it no longer increments as badly.
However now when scores are tied it takes the number of tied scores minus 1 to increment.
See attached picture, showing three tied in 7th place so next should be 10th, but its calculated as 9th.
Also six tied in 9th place, so next should be 15th but it makes it 14th.

Thanks for looking at this.

<img width="920" alt="capture" src="https://cloud.githubusercontent.com/assets/26622706/24246145/e112e638-0fbd-11e7-915f-38d6c3a42804.PNG">

**Comment by Pezmc** [comment]
Thanks for the breakdown, I've fixed the bug, and added some other polish. 

Can you check this looks fixed to you?

**Comment by Conarus** [comment]
Works perfectly now.
Thanks so much for this!!!!
